# .github/workflows/lint.yml
name: GDScript Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install gdtoolkit
      - name: Run gdformat
        run: |
          gdformat --check .
